Fix python2 bug parsing boolean config flag
ConfigParser.getboolean() does not support kwargs in python2, resulting
in TypeError: getboolean() got an unexpected keyword argument 'fallback'

Fix by checking checking if the option exists rather than using fallback